### PR TITLE
Sticky updates

### PR DESCRIPTION
**Pull request by wicz**
As discussed in #27, admins can mark articles as sticky so they appear at the top of the list.

### CODE REVIEW

**Comment by jordanbyron** [comment]
@wicz this was spot on. I just made a few minor changes to the icon. Thanks for working on this :smile:

**Comment by practicingruby** [comment]
I can make articles sticky, but I don't see an icon on them. Did that not get rolled?

**Comment by jordanbyron** [comment]
> I can make articles sticky, but I don't see an icon on them. Did that not get rolled?

Yes it did. Which article did you make sticky? The change I made to indicate public vs private articles currently takes precedence over sticky icons. Maybe that's what you were seeing?

**Comment by practicingruby** [comment]
PEBKAC. I had thought I made sticky the top article on the page, but it was just on the top because it was newest :)

**Pull request merged**
