### PR TITLE
Highlight articles

### PR DESCRIPTION
**Pull request by utkarshkukreti**
See #14

WIP. Opening pull request for discussion.
- Is that the correct place to add the css code?
- Do you want me to add attr_accessible to the Article model to protect users from highlighting articles they cannot?
- Here's something I cooked up for highlighting the articles - http://cl.ly/2y140V2f3J110J27343U The current css structure doesn't allow (afaik) to highlight the complete area.

### CODE REVIEW

**Comment by jordanbyron** [comment]
@utkarshkukreti, thanks for getting started on this. Unfortunately I don't think I'm going to have time to take a look at this before our [Community week](http://community.mendicantuniversity.org/activities/mending-mendicant-community-week) as I am away all next week.

Let's table this issue until then, and work through your questions on the 13th? Sound ok to you?

**Comment by utkarshkukreti** [comment]
Sure, no problem :smile:

**Comment by jordanbyron** [comment]
I think this is a good start. Very small design points, but I think they will make the highlight effect look better:
- Can we add a very slight rounded corner to the highlighted area. 4px should do the trick
- The user gravatar should have a white background, even when highlighted

@sandal what do you think?

**Comment by practicingruby** [comment]
@jordanbyron  I haven't pulled the latest code (only looked at the mockup), but those changes sound good to me.

**Comment by jordanbyron** [comment]
@sandal great!

@utkarshkukreti I guess I should have answered the rest of your questions :wink2:

> Is that the correct place to add the css code?

Since the css you've added is really generic, you might want to rename `.highlight` to just `.right`. I might already have that defined. It comes in handy anytime you need to right align an element.

> Do you want me to add attr_accessible to the Article model to protect users from highlighting articles they cannot?

I don't think that is necessary, but if you can get it working without too much fuss then go ahead and do it.

---

I think that should be enough to get you on your way. Thanks again for working on this :bowtie:

**Comment by jordanbyron** [comment]
Finished this up since it was so close to being done. Thanks @utkarshkukreti!

**Pull request closed without merging**
